string object_label  # 要识别的物体标签（如 "cup"）

---

# 响应结果
geometry_msgs/Point leftposition      # 物体中心坐标 (x,y,z)
geometry_msgs/Quaternion leftorientation  # 姿态四元数
geometry_msgs/Point rightposition      # 物体中心坐标 (x,y,z)
geometry_msgs/Quaternion rightorientation  # 姿态四元数
bool success                     # 是否识别成功
