parameters:
  object_name:
    type: string
  which_arm:
    type: string
  left_target_orientation_x:
    type: float
  left_target_orientation_y:
    type: float
  left_target_orientation_z:
    type: float
  left_target_orientation_w:
    type: float
  left_target_position_x:
    type: float
  left_target_position_y:
    type: float
  left_target_position_z:
    type: float
  right_target_orientation_x:
    type: float
  right_target_orientation_y:
    type: float
  right_target_orientation_z:
    type: float
  right_target_orientation_w:
    type: float
  right_target_position_x:
    type: float
  right_target_position_y:
    type: float
  right_target_position_z:
    type: float
  crouch_height:
    type: float
  nav_to_target_x:
    type: float
  nav_to_target_y:
    type: float
  nav_to_target_oriention_x:
    type: float
  nav_to_target_oriention_y:
    type: float
  nav_to_target_oriention_z:
    type: float
  nav_to_target_oriention_w:
    type: float

    